[package]
name = "probing-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "probing"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
arrow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
procfs = { workspace = true }
ron = { workspace = true }
rustix = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

clap_complete = { version = "4.5.11", features = ["unstable-dynamic"] }
probing-dpp = { path = "../dpp", features = ["cli"] }
eyre = "0.6"
http-body-util = { version = "0.1" }
hyper = { version = "1.3.1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client", "http1", "tokio"] }
hyperparameter = { version = "0.5.12", default-features = false }
libloading = "0.8.3"
pete = "0.12.0"
rustyline = { version = "14.0.0", default-features = false }
shlex = "1.3.0"
strum = "0.26.3"
tabled = "0.16.0"

[dependencies.clap]
version = "4.5.11"
default-features = false
features = [
    "derive",
    "std",
    "help",
    "usage",
]

[dependencies.nix]
version = "0.29.0"
default-features = false
features = [
    "ptrace",
    "signal",
]
