[package]
name = "probing-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "probing"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
procfs = { workspace = true }
ron = { workspace = true }
rustix = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

env_logger = { version = "0.11.3", default-features = false, features = [
    "humantime",
    "auto-color",
] }
probing-proto = { path = "../proto", default-features = false, features = [] }
eyre = "0.6"
http-body-util = { version = "0.1" }
hyper = { version = "1.3.1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client", "http1", "tokio"] }
libloading = "0.8.3"
pete = "0.12.0"
tabled = { version = "0.17.0", default-features = false, features = ["macros"]}

[dependencies.clap]
version = "4.5.11"
default-features = false
features = ["derive", "std", "help", "usage"]

[dependencies.nix]
version = "0.29.0"
default-features = false
features = ["ptrace", "signal"]
