[package]
name = "probe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
backtrace = { version = "0.3.69", features = ["cpp_demangle", "std"] }
ctor = "0.2.6"
local-ip-address = "0.6.1"
mimalloc = "0.1.42"
nix = { version = "0.29.0", default-features = false, features = ["signal"] }
nu-ansi-term = "0.50.0"
once_cell = "1.19.0"
pprof = { version = "0.13.0", features = ["cpp", "flamegraph"] }
pyo3 = { version = "0.21.2", features = ["abi3", "abi3-py37"] }
signal-hook = { version = "0.3.17", default-features = false, features = [] }
tokio = { version = "1.35.1", default-features = false, features = [
  "net",
  "io-util",
  "rt-multi-thread",
] }
hyper = { version = "1.3.1", features = ["server", "http1"] }
bytes = "1.2"
http-body-util = { version = "0.1" }
pin-project-lite = "0.2"
qstring = "0.7.2"
rust-embed = {version = "8.4.0", features = ["compression"]}
procfs = "0.16.0"
probe-common = { path = "common" }
serde_json = "1.0.117"
anyhow = "1.0.86"
hyperparameter = {version="0.5.10", default-features = false}
ron = "0.8.1"

[build-dependencies]
pyo3-build-config = "0.21.2"

[profile.release]
opt-level = "z"  # Optimize for size.
panic = "unwind"
strip = true     # Automatically strip symbols from the binary.
lto = "fat"
debug = 0
codegen-units = 1

[workspace]
members = ["probe", "app", "cli"]
