[package]
name = "probing"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Performance and Stability Diagnostic Tool for AI Applications"
readme = "README.md"
repository = "https://github.com/reiase/probing"
homepage = "https://github.com/reiase/probing"
keywords = ["debug", "performance", "python"]

[lib]
crate-type = ["cdylib"]

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
anyhow = "1.0.86"
backtrace = { version = "0.3.69", features = ["cpp_demangle", "std"] }
ctor = "0.2.6"
env_logger = { version = "0.11.3", default-features = false, features = [
    "humantime",
] }
http-body-util = { version = "0.1" }
hyper = { version = "1.3.1", features = ["server", "http1"] }
hyperparameter = { version = "0.5.11", default-features = false }
log = "0.4"
nix = { version = "0.29.0", default-features = false, features = ["signal"] }
nu-ansi-term = "0.50.0"
once_cell = "1.19.0"
pin-project-lite = "0.2"
plt-rs = "0.2.0"
pprof = { version = "0.13.0", features = ["cpp", "flamegraph"] }
probing-ppp = { path = "ppp" }
procfs = { version = "0.16.0", default-features = false, features = [] }
pyo3 = { version = "0.21.2", features = ["abi3", "abi3-py37"] }
qstring = "0.7.2"
ron = "0.8.1"
rust-embed = "8.4.0"
serde_json = "1.0.117"
signal-hook = { version = "0.3.17", default-features = false, features = [] }

[dependencies.tokio]
version = "1.35.1"
default-features = false
features = ["net", "io-util", "rt-multi-thread"]

[build-dependencies]
pyo3-build-config = "0.21.2"

[profile.release]
opt-level = "z"   # Optimize for size.
panic = "unwind"
strip = true      # Automatically strip symbols from the binary.
lto = "fat"
debug = 0
codegen-units = 1

[workspace]
members = ["app", "cli"]

[workspace.package]
version = "0.1.5"
authors = ["reiase <reiase@gmail.com>"]
edition = "2021"
license = "GPL3"
