[workspace]
members = [
    "app",
    "probing/cli",
    "probing/core",
    "probing/proto",
    "probing/engine",
    "probing/python",
    "probing/server",
    "probing/legacy",
]

[workspace.package]
version = "0.2.0"
authors = ["reiase <reiase@gmail.com>"]
edition = "2021"
license = "GPL3"

[workspace.dependencies]
anyhow = "1.0"
arrow = { version = "53.2.0", default-features = false, features = [] }
chrono = "0.4"
log = "0.4"
once_cell = "1.19.0"
procfs = { version = "0.16.0", default-features = false, features = ["chrono"] }
ron = "0.8.1"
rustix = { version = "0.38.41", default-features = false, features = [
    "termios",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1.41.1", default-features = false, features = [
    "net",
    "io-util",
    "rt-multi-thread",
] }

[package]
name = "probing"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Performance and Stability Diagnostic Tool for AI Applications"
readme = "README.md"
repository = "https://github.com/reiase/probing"
homepage = "https://github.com/reiase/probing"
keywords = ["debug", "performance", "python"]

[lib]
crate-type = ["cdylib"]

[dependencies]
probing-proto = { path = "probing/proto" }
probing-engine = { path = "probing/engine" }
probing-legacy = { path = "probing/legacy" }
probing-server = { path = "probing/server" }
probing-python = { path = "probing/python" }

log = { workspace = true }
once_cell = { workspace = true }
ron = { workspace = true }

ctor = { version = "0.2.6", features=["used_linker"] }
env_logger = { version = "0.11.3", default-features = false, features = [
    "humantime",
] }
nix = { version = "0.29.0", default-features = false, features = ["signal"] }
pin-project-lite = "0.2"

[build-dependencies]
pyo3-build-config = "0.23.3"

[dev-dependencies]
probing-cli = { path = "probing/cli" }

anyhow = { workspace = true }
arrow = { workspace = true, default-features = false, features = ["csv"] }
pyo3 = { version = "0.23.3", features = [
    "abi3",
    "abi3-py37",
    "auto-initialize",
] }
tokio = { workspace = true }

[profile.release]
opt-level = "z"   # Optimize for size.
panic = "unwind"
strip = true      # Automatically strip symbols from the binary.
lto = "fat"
codegen-units = 1
