[package]
name = "probe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
backtrace = { version = "0.3.69", default-features = false, features = [
    "cpp_demangle",
] }
ctor = "0.2.6"
httparse = { version = "1.8.0", default-features = false, features = [] }
lazy_static = "1.4.0"
local-ip-address = "0.5.6"
nu-ansi-term = "0.49.0"
pprof = { version = "0.13.0", default-features = false, features = [
    "cpp",
    "flamegraph",
] }
rustpython = { version = "0.3.0", default-features = false, features = [
    "zlib",
    "threading",
    "importlib",
    "stdlib",
    "freeze-stdlib",
] }
signal-hook = { version = "0.3.17", default-features = false, features = [] }
tokio = { version = "1.35.1", default-features = false, features = [
    "net",
    "io-util",
    "rt-multi-thread",
] }

[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true
panic = "abort"
