[package]
edition = "2021"
name = "probe"
version = "0.1.0"

[lib]
crate-type = ["dylib", "rlib"]

[features]
default = ["dll_init"]
dll_init = []

[dependencies]
backtrace = { version = "0.3.69", features = [
  "cpp_demangle",
  "coresymbolication",
  "std",
] }
clap = { version = "4.5.4", features = ["std", "derive"] }
ctor = "0.2.6"
lazy_static = "1.4.0"
local-ip-address = "0.6.1"
mimalloc = "0.1.42"
nix = { version = "0.29.0", default-features = false, features = ["signal"] }
nu-ansi-term = "0.50.0"
once_cell = "1.19.0"
pprof = { version = "0.13.0", default-features = false, features = [
  "cpp",
  "flamegraph",
] }
ptrace-inject = { path = "./ptrace-inject" }
pyo3 = { version = "0.21.2", features = [
  "extension-module",
  "abi3",
  "abi3-py37",
] }
signal-hook = { version = "0.3.17", default-features = false, features = [] }
tokio = { version = "1.35.1", default-features = false, features = [
  "net",
  "io-util",
  "rt-multi-thread",
] }
html_render = { path = "./html_render" }
hyper = { version = "1.3.1", features = ["client", "server", "http1", "http2"] }
bytes = "1.2"
http-body-util = { version = "0.1" }
pin-project-lite = "0.2"
qstring = "0.7.2"

[build-dependencies]
pyo3-build-config = "0.21.2"

[profile.release]
lto = true
opt-level = "z" # Optimize for size.
panic = "abort"
strip = true    # Automatically strip symbols from the binary.
