[package]
edition = "2021"
name = "probe"
version = "0.1.0"

[lib]
crate-type = ["dylib", "rlib"]

[features]
default = ["dll_init"]
dll_init = []

[dependencies]
backtrace = {version = "0.3.69", default-features = false, features = [
  "cpp_demangle",
]}
clap = {version = "4.4.7", features = ["derive"]}
ctor = "0.2.6"
dlopen2 = "0.7.0"
httparse = {version = "1.8.0", default-features = false, features = []}
lazy_static = "1.4.0"
local-ip-address = "0.5.6"
nix = {version="0.28.0", features=["signal"]}
nu-ansi-term = "0.49.0"
once_cell = "1.19.0"
pprof = {version = "0.13.0", default-features = false, features = [
  "cpp",
  "flamegraph",
]}
ptrace-inject = {path = "./ptrace-inject"}
pyo3 = {version = "0.21.2", features = ["extension-module", "abi3", "abi3-py37"]}
signal-hook = {version = "0.3.17", default-features = false, features = []}
tokio = {version = "1.35.1", default-features = false, features = [
  "net",
  "io-util",
  "rt-multi-thread",
]}

[build-dependencies]
pyo3-build-config = "0.21.2"

[profile.release]
lto = true 
opt-level = "z" # Optimize for size.
panic = "abort" 
strip = true # Automatically strip symbols from the binary.
