[package]
name = "probing-engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.86"
arrow = {version="53.2", default-features = false}
async-trait = "0.1.83"
datafusion = {version = "42.2.0", default-features = false, features = []}
futures = "0.3.31"
log = "0.4"
once_cell = "1.19.0"
procfs = { version = "0.16.0", default-features = false, features = ["chrono"] }
rmesg = "1.0.21"
ron = "0.8.1"
use = "0.0.1-pre.0"

[dependencies.tokio]
version = "1.35.1"
default-features = false
features = ["net", "io-util", "rt-multi-thread"]
