[package]
name = "app"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.leptonic]
js-dir = "public/js"
style-dir = "style"

[dependencies]
console_error_panic_hook = "0.1.7"
serde_json = "1.0.117"
thiserror = "1.0.56"

[dependencies.gloo-net]
version = "0.6.0"
features = ["http"]

[dependencies.leptonic]
git = "https://github.com/lpotthast/leptonic.git"
rev = "6c2959f"
features = []

[dependencies.leptos]
version = "0.6.13"
features = ["csr"]

[dependencies.leptos_meta]
version = "0.6.13"
features = []
default-features = false

[dependencies.leptos_router]
version = "0.6.13"
features = ["csr"]

[dependencies.ppp]
path = "../ppp"
features = []

[dependencies.serde]
version = "1"
features = ["derive"]

[features]
debug = []

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
strip = true

[profile.release.package]

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
