[package]
name = "app"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
serde_json = "1.0.117"
thaw = {version="0.3.4", features=["csr"]}
thiserror = "1.0.56"
icondata = { version = "0.4.0", default-features = false, features = [
    "ant-design-icons",
    "box-icons",
    "lucide",
] }
console_log = "1"
log = "0.4"
leptos-struct-table = "0.13.1"

[dependencies.gloo-net]
version = "0.6.0"
features = ["http"]

[dependencies.leptos]
version = "0.6.15"
features = ["csr"]

[dependencies.leptos_meta]
version = "0.6.15"
features = ["csr"]
default-features = false

[dependencies.leptos_router]
version = "0.6.15"
features = ["csr"]

[dependencies.dpp]
path = "../dpp"
features = []

[dependencies.serde]
version = "1"
features = ["derive"]

[features]
debug = []

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
strip = true

[profile.release.package]

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
