[package]
name = "probing-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[profile.dev]
# Potential to opt-in on higher optimization for our code. This may increase incremental compilation times, but will reduce binaty size.
opt-level = 0
[profile.dev.package."*"]
# High optimization for our dependencies. This should increase performance drastically whithout hitting our incremental compilation times.
# This will lead to obscure error messages from third party libraries. Comment this out when experiencing a tricky bug.
opt-level = 3

[profile.release]
opt-level = "z"
lto = "fat"
debug = 0
strip = true
codegen-units = 1

[features]
debug = []

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-net = {version = "0.6.0", features = ["http"] }
# leptonic = { version = "0.5.0", features = ["csr"] }
leptonic = { git = "https://github.com/lpotthast/leptonic.git", rev = "6c2959f" }
leptos = { version = "0.6.13", features = ["csr"] }
leptos_meta = { version = "0.6.13", features = ["csr"] }
leptos_router = { version = "0.6.13", features = ["csr"] }
thiserror = "1.0.56"
serde = { version = "1", features = ["derive"] }
probing-ppp = {path="../ppp"}
serde_json = "1.0.117"

[package.metadata.leptonic]
# REQUIRED: Leptonic's build-script will copy the Leptonic themes to this directory. Relative to your project root.
style-dir = "style"

# REQUIRED: Leptonic's build-script will copy static JS dependencies to this directory. Relative to your project root.
# Leptonic's `<Root>` component expects JS files to be available at a "js" directory at runtime (for dynamic script includes). Specify a different prop value if you choose a non-stadard location here. 
js-dir = "public/js"
