[package]
name = "probing-server"
description = "Probing Server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
probing-core = { path = "../core" }
probing-engine = { path = "../engine" }

anyhow = { workspace = true }
arrow = { workspace = true, default-features=false}
serde_json = { workspace = true }
tokio = { workspace=true }

hyper = { version = "1", features = ["server", "http1"] }
hyperparameter = { version = "0.5.12", default-features = false }
