[package]
name = "probing-server"
description = "Probing Server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
probing-proto = { path = "../proto" }
probing-python = { path = "../python" }
probing-engine = { path = "../engine" }
# probing-legacy = { path = "../legacy" }

anyhow = { workspace = true }
log = { workspace = true }
ron = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

bytes = "1"
hyper = { version = "1", features = ["server", "client", "http1"] }
pin-project-lite = "0.2"
http-body-util = { version = "0.1" }
hyper-util = { version = "0.1", features = ["client", "http1", "tokio"] }
dns-lookup = "2.0.4"
nu-ansi-term = "0.50.0"
qstring = "0.7.2"
include_dir = "=0.7.4"
nix = { version = "0.29.0", default-features = false, features = ["signal"] }
