[package]
name = "probing-server"
description = "Probing Server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
probing-cc = { path = "../cc" }
probing-proto = { path = "../proto" }
probing-python = { path = "../python" }
probing-engine = { path = "../engine" }

anyhow = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

actix = "0.13"
actix-rt = "2"
actix-web = "4"
awc = "3.5.1"
mime = "0.3"
bytes = "1"
dns-lookup = "2.0.4"
include_dir = "=0.7.4"
nix = { version = "0.29.0", default-features = false, features = ["signal"] }
procfs = { workspace = true }
