[package]
name = "probing-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
serde = { workspace = true }
proc-macro2 = "1.0.92"
syn= "2.0"
quote = "1"