[package]
name = "probing-common"
version = "0.1.4"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
clap = { version = "4.5.7", default_features = false, features = [
    "derive",
    "std",
    "help",
    "usage",
] }
