[package]
name = "probing-proto"
description = "Distributed Probe Protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
cli = ["dep:clap"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
minstant = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

clap = { version = "4.5.11", optional=true, default-features = false, features = [
    "derive",
    "std",
    "help",
    "usage",
] }
pco = "0.4.1"

[dev-dependencies]
arrow = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }
serde_json = { workspace = true }

[[bench]]
name = "bench_series"
harness = false
